### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by ElectronicsArchiver** [richrace/highlight-line#104]
Was looking through my installed extension and wanted to contribute,
checked out the repo page for your project and saw you were looking
for someone to help you out, if you are still looking, I'd love to help.

**Comment by ElectronicsArchiver** [comment]
@richrace Thank you, I will get to work right away

**Comment by richrace** [comment]
Hi thanks! 

I was wondering if you'd be up for taking on https://github.com/richrace/highlight-selected also?

**Comment by ElectronicsArchiver** [comment]
@richrace Sure, I planning on updating as many - now Pulsar - packages as possible!

Btw, I might have to disable  ( and later redo ) CI since atom -> pulsar and apm -> ppm 
( though I haven't been able to get ppm to work on my system yet .. )

**Comment by ElectronicsArchiver** [comment]
@richrace Btw, as a collaborator I sadly don't have the 
ability to adjust the following, which is why I'd like
to ask of you to set them:

- Update the description to

  ```
  https://github.com/pulsar-edit package for highlighting the currently selected line.
  ```
  
- Add the following tags:

  - `package`
  - `customization`
  - `highlighting`
  - `pulsar-edit`
  - `pulsar-package`

- Disable the unused `packages` widget

- Disable the unused `projects` & `Wiki` tabs

**Comment by richrace** [comment]
Hopefully this change will give you more freedom.

**Comment by ElectronicsArchiver** [comment]
@richrace Oh, well that works as well, thanks, I will adjust it myself then~

**Comment by ElectronicsArchiver** [comment]
Oh lol, I didn't even realize at first that you create an organization,
while that is nice, now links will have to be updated as well.

( package repository and the like )

**Comment by ElectronicsArchiver** [comment]
@richrace Btw, I'm still in need of asking you to
disable the `projects` / `discussions` tabs, I'm
not able to fully disable them ..

**Comment by richrace** [comment]
> Oh lol, I didn't even realize at first that you create an organization, while that is nice, now links will have to be updated as well.
> 
> ( package repository and the like )

Sorry for that. 

I’ve disabled discussions.

**Comment by ElectronicsArchiver** [comment]
No problem, to give you some more information on my progress:

While all tests still pass and the code should be fine,

- My devtools are broken in pulsar / atom, they won't open, probably a bug

- PPM is supposed to be installed, however it currently isn't, the documentation is not updated yet, so I'm just waiting for any updates ..
 
  ( They have a Discord which would probably be easiest to ask questions, however I don't have it. )

  ( They plan on a matrix server - which I do have - but that's not set up yet .. )

- The GitHub action for setting up pulsar doesn't have a release yet, so I can't specify it in the workflow and the docs aren't updated yet.

**Comment by ElectronicsArchiver** [comment]
@richrace Since you moved the repositories to an org named

`Pulsar-Edit-Highlights` you could also rename 
the repositories and shorten their names.

- `Line`
- `Selection`

**Comment by ElectronicsArchiver** [comment]
@richrace Made a `.GitHub` repository for the organization overview.

https://github.com/Pulsar-Edit-Highlights/.GitHub

Also, what do you think of this simple logo I made:

https://github.com/Pulsar-Edit-Highlights/.GitHub/blob/main/Avatar.svg

**Comment by ElectronicsArchiver** [comment]
@richrace In case the logo is good enough for now, I would
add a png version that you could download and set as the
organizations avatar .. let me know

Updates:

- ( devtools ) Managed to get them to work in Atom, supposedly it's gonna be fixed soon

- The settings didn't show up but still worked, did a lot of research in the old Atom issues and the only thing that seemed relevant was that they reappear when reinstalling the package, which I 'did' ( it was a local symlink ) and after the 3rd time it worked?

  Seems like a bug as well, but if it were the published package it probably wouldn't happen / be a non-problem just inconvenient as it has been up until this point.

- Cleaned up the line package a bit more, found a way to place all resources in the `Resources` folder

**Comment by ElectronicsArchiver** [comment]
@richrace So, about publishing ..

( Only focused on the `line` repo for now )

1. PPM works for me now

   It's installed when installing Pulsar from https://pulsar-edit.dev/docs/

3. It needs a personal access token as you know

4. Since you are the author listed on https://web.pulsar-edit.dev/packages/highlight-line
   I'm guessing your personal accounts access is still the required one

5. No idea if / how you could switch it over to the organization

6. If it was switched, you then would of course need to create a new token for the organization, like on a personal account, there is a section in the settings

7. No idea what permissions it needed anyways, if your token had any specific ones, please let me know, I haven't been able to find anything about it ..

**Comment by ElectronicsArchiver** [comment]
I'll ask them for more details.

**Comment by ElectronicsArchiver** [comment]
I asked for more information and TLDR,
they added a feature request for their
package backend to allow owners of 
packages to transfer ownership to other
account / ORGANIZATIONS.

If this is implemented, you could create
a PPA on the org ( with the `public_repo`
and `read:org` permissions ) so packages
could be updated again!

So basically, wait for them to implement it~

**Comment by richrace** [comment]
I've gone back in time to look how `minimap` transitioned. It seems so straight forward. I've no joy this morning trying to push a new version. See the "simple" change here: https://github.com/atom-minimap/minimap/commit/fa68337a0d791f8582f7ba0d929965e674de2217#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

I don't know if the `ppm` is having trouble?

`Creating new version failed: The package.json at owner/repo isn't valid.` is the error I'm getting.

I've tried with my `ppm` PAT, my personal ORG PAT as well.

**Comment by richrace** [comment]
The PAT looks like it has the correct permissions 🤷 I used that same key to login into `ppm`

Mine:
![Screenshot 2023-01-07 at 12 18 23](https://user-images.githubusercontent.com/1273965/211150310-3239c820-799a-43a5-9875-1ecf069c53e5.png)

Org:
![Screenshot 2023-01-07 at 12 18 49](https://user-images.githubusercontent.com/1273965/211150313-f1fb9cd2-bd74-4d81-bcbc-01d478ae5243.png)

**Comment by ElectronicsArchiver** [comment]
@richrace Thanks for trying, well they are working
on it right now, so maybe let's give them some time
and see if it's getting fixed to a point where it
won't be a pain anymore ..

At least the org PAT is already set up.
