### ISSUE TITLE
Not working with new Shadow DOM

### ISSUE THREAD

**Issue by KylePDavis** [richrace/highlight-line#34]
Just a heads up: highlight-line v0.9.2 doesn't seem to work when the new "Use Shadow DOM" option is enabled.

**Comment by paradox460** [comment]
:+1:

**Comment by michaeljcalkins** [comment]
Works for me too.

![image](https://cloud.githubusercontent.com/assets/8272012/5707958/f434275c-9a41-11e4-8499-7b9dda372a1b.png)

**Comment by richrace** [comment]
Ok, I've published the fix. Sorry, haven't had much time lately. Ideally wanted to get the specs fixed first.
