### ISSUE TITLE
Wrong line highlighted with soft wrap

### ISSUE THREAD

**Issue by bojidar-bg** [richrace/highlight-line#64]
To reproduce:
1. Make a new file
2. Toggle soft wrap form View->Toggle soft wrap
3. Write a very long line, so it wraps
4. Press Home
5. Now the wrong line is highlighted
![image](https://cloud.githubusercontent.com/assets/5276727/6591987/5b55ebc6-c7d0-11e4-9a57-a55720c511ae.png)

**Comment by richrace** [comment]
What OS are you using?

**Comment by bojidar-bg** [comment]
Ubuntu-gnome 14.10. Atom version 0.177.0.

**Comment by richrace** [comment]
Hmm have you updated to the latest Atom and is it still happening couldn't replicate it with Atom 0.187.0

**Comment by bojidar-bg** [comment]
The bug/problem is nonexistent in 0.187.0 :smile:
