### ISSUE TITLE
Underline missing on certain lines

### ISSUE THREAD

**Issue by venkatachalam88** [richrace/highlight-line#72]
Underline missing on exactly line numbers 12, 24, 36... multiples of 12. This affects both underline on particular line and selection border. I'm using Arch linux OS.

**Comment by richrace** [comment]
That is odd. What file type was this on? Works fine on Ubuntu on those lines here.

**Comment by vadviktor** [comment]
On Xubuntu with Atom `1.0.15` I also get this effect. I recorded it here: https://www.youtube.com/watch?v=trQK6uoDJ1g

**Comment by richarddewit** [comment]
Mine gets hidden on multiples of 6

**Comment by richrace** [comment]
Is this still an issue?

**Comment by vadviktor** [comment]
Yes it still disappears on every second line just like before. Xubuntu Xenial, Atom 1.7.3
