### ISSUE TITLE
Can't turn off the line highlighting

### ISSUE THREAD

**Issue by bobrocke** [richrace/highlight-line#74]
I'd like the line number in the gutter to be highlighted, but not the text of the line itself.

I tried this, but it had no effect:

```
atom-text-editor::shadow {
  // The cursor line important to use rgba for opacity, also requires !important
  // to override any theme.
  .line.highlight-line {
    background: none !important;
  }
}
```
What did I miss?

**Comment by richrace** [comment]
This package doesn't actually highlight the gutter.

**Comment by bobrocke** [comment]
So, highlight-line doesn't highlight lines? Do you know what does?

**Comment by richrace** [comment]
It does highlight lines; but not the gutter. This package only deals with the `line` part in the picture below; and does nothing with the `gutter`.

![gutter-line](https://cloud.githubusercontent.com/assets/1273965/11168746/5088c180-8b95-11e5-805f-65b18632a600.png)

**Comment by bobrocke** [comment]
Good! So why doesn't the example code turn off line highlighting?

**Comment by richrace** [comment]
It does (well the code in the screenshot uncommented). 

But your theme might have styling on `.cursor-line` which gives a primitive highlight line. (Out at the moment and can't remember the exact class).

**Comment by bobrocke** [comment]
OK! I see where it is. Thanks for the clue.
