### ISSUE TITLE
when use cmd-L to select line, selection border will select one more line

### ISSUE THREAD

**Issue by jesseminn** [richrace/highlight-line#76]
I enabled selection border, if I select multiple lines by cursor, the border works fine; if I select line by using cmd-L, it will select one more line on the bottom.
maybe you can check the video: https://dl.dropboxusercontent.com/u/12302850/highlight-line-issue.mov

**Comment by cliffordfajardo** [comment]
Here's of what visual of what @jesseminn is reffering to:

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/6743796/12468288/089c8a56-bf97-11e5-9de6-526705055c48.gif)

**Details:**
Selecting text with cursor properly displays the selection border as it should. 
However, using the keyboard shortcut [cmd + l] to select lines adds the bottom selection line one line below of where it should be.
