### ISSUE TITLE
Multi-select background isn't cleared after ESC

### ISSUE THREAD

**Issue by alexandernst** [richrace/highlight-line#79]
Selecting a few lines of code with `ctrl+d` and then hitting `esc` doesn't clear the highlight/background of the lines.

visual example:
![](http://ibin.co/2W9Wstnr806c)

**Comment by amayer5125** [comment]
Hitting esc doesnt clear the selection no matter how I select the lines. either using ctrl + d, click and drag, shift + up/down.
